# Generated by Django 6.0.7 on 2026-07-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service médical',
                'verbose_name_plural': 'Services médicaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TarifService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_patient', models.CharField(choices=[('ordinaire', 'Ordinaire'), ('mutualiste', 'Mutualiste'), ('indigent', 'Indigent')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gratuit', models.BooleanField(default=False)),
                ('date_effet', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='services.servicemedical')),
            ],
            options={
                'verbose_name': 'Tarif de service',
                'verbose_name_plural': 'Tarifs de service',
                'ordering': ['-date_effet'],
                'constraints': [models.UniqueConstraint(fields=('service', 'categorie_patient', 'date_effet'), name='unique_tarif_service_categorie_date')],
            },
        ),
    ]
