# Generated by Django 6.0.7 on 2026-07-15 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('annulation', 'Annulation')], max_length=20)),
                ('modele_cible', models.CharField(help_text='Nom du modèle concerné (ex: Ticket, Patient)', max_length=100)),
                ('objet_id', models.CharField(help_text="Identifiant de l'objet concerné", max_length=50)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text="Détails de l'action (motif, anciennes/nouvelles valeurs...)")),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée du journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date_heure'],
            },
        ),
    ]
