# Generated by Django 6.0.7 on 2026-07-15 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('cloturee', 'Clôturée')], default='ouverte', max_length=20)),
                ('sync_status', models.CharField(choices=[('synchronise', 'Synchronisé'), ('en_attente', 'En attente de synchronisation')], default='synchronise', max_length=20)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut_file', models.CharField(choices=[('en_attente', 'En attente'), ('appele', 'Appelé'), ('traite', 'Traité'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('statut_paiement', models.CharField(choices=[('paye', 'Payé'), ('en_attente_remboursement', 'En attente remboursement'), ('gratuit_indigent', 'Gratuit — indigent')], default='paye', max_length=30)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('motif_annulation', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='patients.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='services.servicemedical')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='caisse.caissesession')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-date'],
            },
        ),
    ]
