# Generated by Django 6.0.7 on 2026-07-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
                ('commune', models.ForeignKey(blank=True, help_text='Commune parente (optionnel, pour la hiérarchie quartier/village -> commune)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quartiers', to='localites.localite')),
            ],
            options={
                'verbose_name': 'Localité',
                'verbose_name_plural': 'Localités',
                'ordering': ['nom'],
            },
        ),
    ]
