# Generated by Django 6.0.7 on 2026-07-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identifiant technique (ex: ordinaire)', max_length=30, unique=True)),
                ('libelle', models.CharField(help_text='Nom affiche (ex: Ordinaire)', max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categorie de patient',
                'verbose_name_plural': 'Categories de patient',
                'ordering': ['libelle'],
            },
        ),
    ]
